## Datatypes and Attributs

In [1]:
import numpy as np

In [2]:
# Numpy main datatype is ndarray(n dimentional array)
Array1 = np.array([1,2,3])
Array1

array([1, 2, 3])

In [3]:
type(Array1)

numpy.ndarray

In [4]:
Array2 = np.array([[1,2,3], [4,5,6]])

In [7]:
Array3 = np.array([[[1,2,3],
                    [4,5,6,], 
                    [7,8,9]],
                    [[10,11,12],
                    [13,14,15],
                    [16,17,18]]])
Array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
Array1.shape

(2, 3, 3)

In [10]:

Array2.shape

(2, 3)

In [11]:

Array3.shape

(2, 3, 3)

In [12]:
Array1.ndim

1

In [13]:
Array1.ndim, Array2.ndim, Array3.ndim

(1, 2, 3)

In [14]:
Array1.dtype, Array2.dtype, Array3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [15]:
Array1.size, Array2.size, Array3.size

(3, 6, 18)

In [16]:
type(Array1), type(Array2), type(Array3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Create a Dataframe from Numpy Array

In [18]:
import pandas as pd

df = pd.DataFrame(Array2)
df

0  1  2
0  1  2  3
1  4  5  6

##Creating Arrays

In [20]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype

dtype('int32')

In [23]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
type(ones)

numpy.ndarray

In [25]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0, 10, (3,5))
random_array

array([[7, 4, 2, 7, 1],
       [8, 4, 4, 4, 4],
       [7, 2, 6, 2, 6]])

In [31]:
random_array.size

15

In [32]:
random_array.shape

(3, 5)

In [34]:
np.random.random((5,3))

array([[0.73984963, 0.85040395, 0.66071272],
       [0.21480857, 0.20807184, 0.02447681],
       [0.70515718, 0.24150138, 0.2324542 ],
       [0.71101642, 0.77880601, 0.4948606 ],
       [0.69226099, 0.50778673, 0.49086595]])

In [39]:
#pseudo-random numbers
np.random.seed(0)

In [44]:
np.random.seed(0) #Stops progream regenerating randoms again and again
seed_random_array = np.random.randint(0, 10, (3,5))
seed_random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

#Viewing arrays and martices

In [45]:
np.unique(seed_random_array) #find random occurings

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
 seed_random_array[0] #return row of given index

array([5, 0, 3, 3, 7])

In [50]:
seed_random_array[:2, :2] #values in first 2 rows and first 2 cols

array([[5, 0],
       [9, 3]])