## An end to end scikit lean workflow

In [1]:
# 1 Get Data Ready
import pandas as pd
import numpy as np
Heart_Disease = pd.read_csv("heart-disease.csv")
Heart_Disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [2]:
# Create X (features matrix) a feature is an input variable
X = Heart_Disease.drop("target", axis = 1)  #X is kind of features in sk leaern || axis=1 means we are skipping col 0 means rows

# Create Y (labels) a label is the output variable
Y = Heart_Disease["target"]

In [3]:
# 2 Choose the right model and hyperpameters(dials on model to tune it)
#Ensemble learning is a machine learning technique that combines the predictions of multiple models to create a more accurate and robust model. The idea is that by combining the strengths of multiple models, we can reduce the errors that any individual model might make.

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# We keep default hyper prams
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [4]:
# 3 Fit the model to data
from sklearn.model_selection import  train_test_split #The train_test_split function from the sklearn.model_selection library in Python splits arrays or matrices into random subsets for train and test data, respectively. It is a commonly used function in machine learning for evaluating the performance of a model.
# X: The features of the dataset.
# y: The labels of the dataset.
# y: The labels of the dataset.
# random_state: A random number generator seed.
# test_size argument is set to 0.2, which means that 20% of the dataset will be used for the test set and 80% of the dataset will be used for the training set. 

#X_train: The features of the training set.
#X_test: The features of the test set.
#Y_train: The labels of the training set.
#Y_test: The labels of the test set.
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [5]:
clf.fit(X_train, Y_train)

RandomForestClassifier()

In [6]:
#3 Make a predection
#Y_label =  clf.predict(np.array[0,2,3,4]) #"object is not subscriptable" in Python sklearn means that you are trying to access an element of an object that does not support indexing.
# Getting error here because our araay looks nothing like X_train,,,, just a thing that clf will predict on data that looks like training data
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
270   46    1   0       120   249    0        0      144      0      0.8   
252   62    0   0       138   294    1        1      106      0      1.9   
110   64    0   0       180   325    0        1      154      1      0.0   
243   57    1   0       152   274    0        1       88      1      1.2   
265   66    1   0       112   212    0        0      132      1      0.1   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
73    51    1   0       140   261    0        0      186      1      0.0   
113   43    1   0       110   211    0        1      161      0      0.0   
40    51    0   2       140   308    0        0      142      0      1.5   
104   50    1   2       129   196    0        1      163      0      0.0   
241   59    0   0       174   249    0        1      143      1      0.0   

     slope  ca  thal  
270      2   0     3  
252      1   3     2  
110      2   0     2  
243      1   1     3  
265      2   1     2  
..     ...  ..   ...  
73       2   0     2  
113      2   0     3  
40       2   1     2  
104      2   0     2  
241      1   0     2  

[242 rows x 13 columns]

In [7]:
Y_preds =  clf.predict(X_test)
Y_preds

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1], dtype=int64)

In [8]:
# 4 Evaluate model on training data and test data
clf.score(X_train, Y_train)

1.0

In [9]:
clf.score(X_test, Y_test)

0.8032786885245902

In [10]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(Y_test, Y_preds))

              precision    recall  f1-score   support

           0       0.82      0.77      0.79        30
           1       0.79      0.84      0.81        31

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.80      0.80      0.80        61



In [11]:
confusion_matrix(Y_test, Y_preds)

array([[23,  7],
       [ 5, 26]], dtype=int64)

In [12]:
accuracy_score(Y_test, Y_preds)

0.8032786885245902

In [13]:
#5 Improve a model
# Try different amout of n_estimators
np.random.seed(0)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators..")
    clf = RandomForestClassifier(n_estimators=i).fit(X_test, Y_test)
    print(f"Model accuracy on test set: {clf.score(X_test, Y_test)}%")
    print("")

Trying model with 10 estimators..
Model accuracy on test set: 0.9836065573770492%

Trying model with 20 estimators..
Model accuracy on test set: 1.0%

Trying model with 30 estimators..
Model accuracy on test set: 1.0%

Trying model with 40 estimators..
Model accuracy on test set: 1.0%

Trying model with 50 estimators..
Model accuracy on test set: 1.0%

Trying model with 60 estimators..
Model accuracy on test set: 1.0%

Trying model with 70 estimators..
Model accuracy on test set: 1.0%

Trying model with 80 estimators..
Model accuracy on test set: 1.0%

Trying model with 90 estimators..
Model accuracy on test set: 1.0%



In [14]:
# Save model and load it
import pickle
pickle.dump(clf, open("random_forest_model_1.pkl", "wb"))

In [15]:
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaded_model.score(X_test, Y_test)

1.0

### Making All Data Numerical
## Extended Car Sales Data

In [16]:
Car_Sales = pd.read_csv("car-sales-extended.csv")

In [17]:
# Split
X = Car_Sales.drop("Price", axis=1)
Y = Car_Sales["Price"]

In [18]:
# to convert objects to number other way is to do it dummies = pd.get_dummies(Car_Sales[["Make", "Colour", "Doors"]])
# Turn Categories into numbers

#HotEncoder converts and ColTrans applies to col maybe i don't know yet
from sklearn.preprocessing import OneHotEncoder #One-hot encoding is a technique used to convert categorical data into a numerical format
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)], remainder = "passthrough") #The ColumnTransformer class takes a list of tuples as input. Each tuple in the list specifies the name of the transformer, the transformer object itself, and the list of columns to which the transformer should be applied.
transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [19]:
#Building machine learning model
from sklearn.ensemble import RandomForestRegressor
#Split into training and test 
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(transformed_X, Y, train_size=0.8)

# Fit the model
np.random.seed(123)
model = RandomForestRegressor()
model.fit(X_train, Y_train)

RandomForestRegressor()

In [20]:
model.score(X_test, Y_test)

0.1766125736090549

### Handling missing values

1 Fill them with value (imputation)
2 Remove samples with missing altogether

In [22]:
Car_Sales_Missing = pd.read_csv("car-sales-extended-missing-data.csv")
Car_Sales_Missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [33]:
Car_Sales_Missing.isna().sum()
X=Car_Sales_Missing.drop("Price", axis=1)
Y=Car_Sales_Missing["Price"]

In [45]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)], remainder = "passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X;