## An end to end scikit lean workflow

In [50]:
# 1 Get Data Ready
import pandas as pd
import numpy as np
Heart_Disease = pd.read_csv("heart-disease.csv")
Heart_Disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [51]:
# Create X (features matrix) a feature is an input variable
X = Heart_Disease.drop("target", axis = 1)  #X is kind of features in sk leaern || axis=1 means we are skipping col 0 means rows

# Create Y (labels) a label is the output variable
Y = Heart_Disease["target"]

In [52]:
# 2 Choose the right model and hyperpameters(dials on model to tune it)
#Ensemble learning is a machine learning technique that combines the predictions of multiple models to create a more accurate and robust model. The idea is that by combining the strengths of multiple models, we can reduce the errors that any individual model might make.

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# We keep default hyper prams
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [53]:
# 3 Fit the model to data
from sklearn.model_selection import  train_test_split #The train_test_split function from the sklearn.model_selection library in Python splits arrays or matrices into random subsets for train and test data, respectively. It is a commonly used function in machine learning for evaluating the performance of a model.
# X: The features of the dataset.
# y: The labels of the dataset.
# y: The labels of the dataset.
# random_state: A random number generator seed.
# test_size argument is set to 0.2, which means that 20% of the dataset will be used for the test set and 80% of the dataset will be used for the training set. 

#X_train: The features of the training set.
#X_test: The features of the test set.
#Y_train: The labels of the training set.
#Y_test: The labels of the test set.
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [54]:
clf.fit(X_train, Y_train)

RandomForestClassifier()

In [55]:
#3 Make a predection
#Y_label =  clf.predict(np.array[0,2,3,4]) #"object is not subscriptable" in Python sklearn means that you are trying to access an element of an object that does not support indexing.
# Getting error here because our araay looks nothing like X_train,,,, just a thing that clf will predict on data that looks like training data
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
246   56    0   0       134   409    0        0      150      1      1.9   
280   42    1   0       136   315    0        1      125      1      1.8   
272   67    1   0       120   237    0        1       71      0      1.0   
210   57    1   2       128   229    0        0      150      0      0.4   
177   64    1   2       140   335    0        1      158      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
233   64    1   0       120   246    0        0       96      1      2.2   
51    66    1   0       120   302    0        0      151      0      0.4   
1     37    1   2       130   250    0        1      187      0      3.5   
18    43    1   0       150   247    0        1      171      0      1.5   
268   54    1   0       122   286    0        0      116      1      3.2   

     slope  ca  thal  
246      1   2     3  
280      1   0     1  
272      1   0     2  
210      1   1     3  
177      2   0     2  
..     ...  ..   ...  
233      0   1     2  
51       1   0     2  
1        0   0     2  
18       2   0     2  
268      1   2     2  

[242 rows x 13 columns]

In [56]:
Y_preds =  clf.predict(X_test)
Y_preds

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [57]:
# 4 Evaluate model on training data and test data
clf.score(X_train, Y_train)

1.0

In [58]:
clf.score(X_test, Y_test)

0.7540983606557377

In [59]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(Y_test, Y_preds))

              precision    recall  f1-score   support

           0       0.70      0.82      0.75        28
           1       0.82      0.70      0.75        33

    accuracy                           0.75        61
   macro avg       0.76      0.76      0.75        61
weighted avg       0.76      0.75      0.75        61



In [60]:
confusion_matrix(Y_test, Y_preds)

array([[23,  5],
       [10, 23]], dtype=int64)

In [61]:
accuracy_score(Y_test, Y_preds)

0.7540983606557377

In [62]:
#5 Improve a model
# Try different amout of n_estimators
np.random.seed(0)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators..")
    clf = RandomForestClassifier(n_estimators=i).fit(X_test, Y_test)
    print(f"Model accuracy on test set: {clf.score(X_test, Y_test)}%")
    print("")

Trying model with 10 estimators..
Model accuracy on test set: 0.9836065573770492%

Trying model with 20 estimators..
Model accuracy on test set: 1.0%

Trying model with 30 estimators..
Model accuracy on test set: 1.0%

Trying model with 40 estimators..
Model accuracy on test set: 1.0%

Trying model with 50 estimators..
Model accuracy on test set: 1.0%

Trying model with 60 estimators..
Model accuracy on test set: 1.0%

Trying model with 70 estimators..
Model accuracy on test set: 1.0%

Trying model with 80 estimators..
Model accuracy on test set: 1.0%

Trying model with 90 estimators..
Model accuracy on test set: 1.0%



In [63]:
# Save model and load it
import pickle
pickle.dump(clf, open("random_forest_model_1.pkl", "wb"))

In [64]:
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaded_model.score(X_test, Y_test)

1.0

### Making All Data Numerical
## Extended Car Sales Data

In [70]:
Car_Sales = pd.read_csv("car-sales-extended.csv")

In [66]:
# Split
X = Car_Sales.drop("Price", axis=1)
Y = Car_Sales["Price"]

In [67]:
# to convert objects to number other way is to do it dummies = pd.get_dummies(Car_Sales[["Make", "Colour", "Doors"]])
# Turn Categories into numbers


from sklearn.preprocessing import OneHotEncoder #One-hot encoding is a technique used to convert categorical data into a numerical format
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)], remainder = "passthrough") #The ColumnTransformer class takes a list of tuples as input. Each tuple in the list specifies the name of the transformer, the transformer object itself, and the list of columns to which the transformer should be applied.
transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [68]:
#Building machine learning model
from sklearn.ensemble import RandomForestRegressor
#Split into training and test 
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(transformed_X, Y, train_size=0.8)

# Fit the model
np.random.seed(123)
model = RandomForestRegressor()
model.fit(X_train, Y_train)

RandomForestRegressor()

In [69]:
model.score(X_test, Y_test)

0.1766125736090549